/*
IDaaS API

Testing MyAccountAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apiidaassdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_apiidaassdk_MyAccountAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MyAccountAPIService GetMydexIdFromMyAccountSvt", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var svt string

		resp, httpRes, err := apiClient.MyAccountAPI.GetMydexIdFromMyAccountSvt(context.Background(), svt).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
