/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
	"fmt"
)

// checks if the InviteRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteRequestBody{}

// InviteRequestBody Request body for storing and sending an identifier invite
type InviteRequestBody struct {
	// The parent identifier
	Identifier string `json:"identifier"`
	// The application URL
	AppUrl string `json:"app_url"`
	// The OAuth2 client ID
	ClientId string `json:"client_id"`
	// The connection NID
	ConNid string `json:"con_nid"`
	// The organization ID
	OrgId string `json:"org_id"`
	// The project ID
	ProjectId string `json:"project_id"`
	// The item ID
	ItemId string `json:"item_id"`
	// The type of invitation
	Type string `json:"type"`
	// Email message content
	MessageEmail string `json:"message_email"`
	// SMS message content
	MessageSms NullableString `json:"message_sms,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InviteRequestBody InviteRequestBody

// NewInviteRequestBody instantiates a new InviteRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteRequestBody(identifier string, appUrl string, clientId string, conNid string, orgId string, projectId string, itemId string, type_ string, messageEmail string) *InviteRequestBody {
	this := InviteRequestBody{}
	this.Identifier = identifier
	this.AppUrl = appUrl
	this.ClientId = clientId
	this.ConNid = conNid
	this.OrgId = orgId
	this.ProjectId = projectId
	this.ItemId = itemId
	this.Type = type_
	this.MessageEmail = messageEmail
	return &this
}

// NewInviteRequestBodyWithDefaults instantiates a new InviteRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteRequestBodyWithDefaults() *InviteRequestBody {
	this := InviteRequestBody{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *InviteRequestBody) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *InviteRequestBody) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *InviteRequestBody) SetIdentifier(v string) {
	o.Identifier = v
}

// GetAppUrl returns the AppUrl field value
func (o *InviteRequestBody) GetAppUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppUrl
}

// GetAppUrlOk returns a tuple with the AppUrl field value
// and a boolean to check if the value has been set.
func (o *InviteRequestBody) GetAppUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppUrl, true
}

// SetAppUrl sets field value
func (o *InviteRequestBody) SetAppUrl(v string) {
	o.AppUrl = v
}

// GetClientId returns the ClientId field value
func (o *InviteRequestBody) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *InviteRequestBody) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *InviteRequestBody) SetClientId(v string) {
	o.ClientId = v
}

// GetConNid returns the ConNid field value
func (o *InviteRequestBody) GetConNid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConNid
}

// GetConNidOk returns a tuple with the ConNid field value
// and a boolean to check if the value has been set.
func (o *InviteRequestBody) GetConNidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConNid, true
}

// SetConNid sets field value
func (o *InviteRequestBody) SetConNid(v string) {
	o.ConNid = v
}

// GetOrgId returns the OrgId field value
func (o *InviteRequestBody) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *InviteRequestBody) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *InviteRequestBody) SetOrgId(v string) {
	o.OrgId = v
}

// GetProjectId returns the ProjectId field value
func (o *InviteRequestBody) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *InviteRequestBody) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *InviteRequestBody) SetProjectId(v string) {
	o.ProjectId = v
}

// GetItemId returns the ItemId field value
func (o *InviteRequestBody) GetItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value
// and a boolean to check if the value has been set.
func (o *InviteRequestBody) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemId, true
}

// SetItemId sets field value
func (o *InviteRequestBody) SetItemId(v string) {
	o.ItemId = v
}

// GetType returns the Type field value
func (o *InviteRequestBody) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InviteRequestBody) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InviteRequestBody) SetType(v string) {
	o.Type = v
}

// GetMessageEmail returns the MessageEmail field value
func (o *InviteRequestBody) GetMessageEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageEmail
}

// GetMessageEmailOk returns a tuple with the MessageEmail field value
// and a boolean to check if the value has been set.
func (o *InviteRequestBody) GetMessageEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageEmail, true
}

// SetMessageEmail sets field value
func (o *InviteRequestBody) SetMessageEmail(v string) {
	o.MessageEmail = v
}

// GetMessageSms returns the MessageSms field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteRequestBody) GetMessageSms() string {
	if o == nil || IsNil(o.MessageSms.Get()) {
		var ret string
		return ret
	}
	return *o.MessageSms.Get()
}

// GetMessageSmsOk returns a tuple with the MessageSms field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteRequestBody) GetMessageSmsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MessageSms.Get(), o.MessageSms.IsSet()
}

// HasMessageSms returns a boolean if a field has been set.
func (o *InviteRequestBody) HasMessageSms() bool {
	if o != nil && o.MessageSms.IsSet() {
		return true
	}

	return false
}

// SetMessageSms gets a reference to the given NullableString and assigns it to the MessageSms field.
func (o *InviteRequestBody) SetMessageSms(v string) {
	o.MessageSms.Set(&v)
}
// SetMessageSmsNil sets the value for MessageSms to be an explicit nil
func (o *InviteRequestBody) SetMessageSmsNil() {
	o.MessageSms.Set(nil)
}

// UnsetMessageSms ensures that no value is present for MessageSms, not even an explicit nil
func (o *InviteRequestBody) UnsetMessageSms() {
	o.MessageSms.Unset()
}

func (o InviteRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	toSerialize["app_url"] = o.AppUrl
	toSerialize["client_id"] = o.ClientId
	toSerialize["con_nid"] = o.ConNid
	toSerialize["org_id"] = o.OrgId
	toSerialize["project_id"] = o.ProjectId
	toSerialize["item_id"] = o.ItemId
	toSerialize["type"] = o.Type
	toSerialize["message_email"] = o.MessageEmail
	if o.MessageSms.IsSet() {
		toSerialize["message_sms"] = o.MessageSms.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InviteRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
		"app_url",
		"client_id",
		"con_nid",
		"org_id",
		"project_id",
		"item_id",
		"type",
		"message_email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteRequestBody := _InviteRequestBody{}

	err = json.Unmarshal(data, &varInviteRequestBody)

	if err != nil {
		return err
	}

	*o = InviteRequestBody(varInviteRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "identifier")
		delete(additionalProperties, "app_url")
		delete(additionalProperties, "client_id")
		delete(additionalProperties, "con_nid")
		delete(additionalProperties, "org_id")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "item_id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "message_email")
		delete(additionalProperties, "message_sms")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInviteRequestBody struct {
	value *InviteRequestBody
	isSet bool
}

func (v NullableInviteRequestBody) Get() *InviteRequestBody {
	return v.value
}

func (v *NullableInviteRequestBody) Set(val *InviteRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteRequestBody(val *InviteRequestBody) *NullableInviteRequestBody {
	return &NullableInviteRequestBody{value: val, isSet: true}
}

func (v NullableInviteRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


