/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
	"fmt"
)

// checks if the NotifyMemberRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotifyMemberRequestBody{}

// NotifyMemberRequestBody Request body for sending a notification to a member
type NotifyMemberRequestBody struct {
	IdentifierAuth IdentifierAuthObject `json:"identifier_auth"`
	// Email message content
	MessageEmail string `json:"message_email"`
	// SMS message content
	MessageSms NullableString `json:"message_sms,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NotifyMemberRequestBody NotifyMemberRequestBody

// NewNotifyMemberRequestBody instantiates a new NotifyMemberRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotifyMemberRequestBody(identifierAuth IdentifierAuthObject, messageEmail string) *NotifyMemberRequestBody {
	this := NotifyMemberRequestBody{}
	this.IdentifierAuth = identifierAuth
	this.MessageEmail = messageEmail
	return &this
}

// NewNotifyMemberRequestBodyWithDefaults instantiates a new NotifyMemberRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotifyMemberRequestBodyWithDefaults() *NotifyMemberRequestBody {
	this := NotifyMemberRequestBody{}
	return &this
}

// GetIdentifierAuth returns the IdentifierAuth field value
func (o *NotifyMemberRequestBody) GetIdentifierAuth() IdentifierAuthObject {
	if o == nil {
		var ret IdentifierAuthObject
		return ret
	}

	return o.IdentifierAuth
}

// GetIdentifierAuthOk returns a tuple with the IdentifierAuth field value
// and a boolean to check if the value has been set.
func (o *NotifyMemberRequestBody) GetIdentifierAuthOk() (*IdentifierAuthObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentifierAuth, true
}

// SetIdentifierAuth sets field value
func (o *NotifyMemberRequestBody) SetIdentifierAuth(v IdentifierAuthObject) {
	o.IdentifierAuth = v
}

// GetMessageEmail returns the MessageEmail field value
func (o *NotifyMemberRequestBody) GetMessageEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageEmail
}

// GetMessageEmailOk returns a tuple with the MessageEmail field value
// and a boolean to check if the value has been set.
func (o *NotifyMemberRequestBody) GetMessageEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageEmail, true
}

// SetMessageEmail sets field value
func (o *NotifyMemberRequestBody) SetMessageEmail(v string) {
	o.MessageEmail = v
}

// GetMessageSms returns the MessageSms field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NotifyMemberRequestBody) GetMessageSms() string {
	if o == nil || IsNil(o.MessageSms.Get()) {
		var ret string
		return ret
	}
	return *o.MessageSms.Get()
}

// GetMessageSmsOk returns a tuple with the MessageSms field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NotifyMemberRequestBody) GetMessageSmsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MessageSms.Get(), o.MessageSms.IsSet()
}

// HasMessageSms returns a boolean if a field has been set.
func (o *NotifyMemberRequestBody) HasMessageSms() bool {
	if o != nil && o.MessageSms.IsSet() {
		return true
	}

	return false
}

// SetMessageSms gets a reference to the given NullableString and assigns it to the MessageSms field.
func (o *NotifyMemberRequestBody) SetMessageSms(v string) {
	o.MessageSms.Set(&v)
}
// SetMessageSmsNil sets the value for MessageSms to be an explicit nil
func (o *NotifyMemberRequestBody) SetMessageSmsNil() {
	o.MessageSms.Set(nil)
}

// UnsetMessageSms ensures that no value is present for MessageSms, not even an explicit nil
func (o *NotifyMemberRequestBody) UnsetMessageSms() {
	o.MessageSms.Unset()
}

func (o NotifyMemberRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotifyMemberRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier_auth"] = o.IdentifierAuth
	toSerialize["message_email"] = o.MessageEmail
	if o.MessageSms.IsSet() {
		toSerialize["message_sms"] = o.MessageSms.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NotifyMemberRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier_auth",
		"message_email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotifyMemberRequestBody := _NotifyMemberRequestBody{}

	err = json.Unmarshal(data, &varNotifyMemberRequestBody)

	if err != nil {
		return err
	}

	*o = NotifyMemberRequestBody(varNotifyMemberRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "identifier_auth")
		delete(additionalProperties, "message_email")
		delete(additionalProperties, "message_sms")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotifyMemberRequestBody struct {
	value *NotifyMemberRequestBody
	isSet bool
}

func (v NullableNotifyMemberRequestBody) Get() *NotifyMemberRequestBody {
	return v.value
}

func (v *NullableNotifyMemberRequestBody) Set(val *NotifyMemberRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableNotifyMemberRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableNotifyMemberRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotifyMemberRequestBody(val *NotifyMemberRequestBody) *NullableNotifyMemberRequestBody {
	return &NullableNotifyMemberRequestBody{value: val, isSet: true}
}

func (v NullableNotifyMemberRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotifyMemberRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


