/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
	"fmt"
)

// checks if the IdentifyRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentifyRequestBody{}

// IdentifyRequestBody Request body for identification URL setup
type IdentifyRequestBody struct {
	// The connection NID
	ConnectionNid string `json:"connection_nid"`
	// The hashed connection token
	ConnectionTokenHash string `json:"connection_token_hash"`
	// The URL to return to after identification
	ReturnTo string `json:"return_to"`
	// A unique ID representing the member in the subscriber's backend
	LinkingToken NullableString `json:"linking_token,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IdentifyRequestBody IdentifyRequestBody

// NewIdentifyRequestBody instantiates a new IdentifyRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentifyRequestBody(connectionNid string, connectionTokenHash string, returnTo string) *IdentifyRequestBody {
	this := IdentifyRequestBody{}
	this.ConnectionNid = connectionNid
	this.ConnectionTokenHash = connectionTokenHash
	this.ReturnTo = returnTo
	return &this
}

// NewIdentifyRequestBodyWithDefaults instantiates a new IdentifyRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentifyRequestBodyWithDefaults() *IdentifyRequestBody {
	this := IdentifyRequestBody{}
	return &this
}

// GetConnectionNid returns the ConnectionNid field value
func (o *IdentifyRequestBody) GetConnectionNid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionNid
}

// GetConnectionNidOk returns a tuple with the ConnectionNid field value
// and a boolean to check if the value has been set.
func (o *IdentifyRequestBody) GetConnectionNidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionNid, true
}

// SetConnectionNid sets field value
func (o *IdentifyRequestBody) SetConnectionNid(v string) {
	o.ConnectionNid = v
}

// GetConnectionTokenHash returns the ConnectionTokenHash field value
func (o *IdentifyRequestBody) GetConnectionTokenHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionTokenHash
}

// GetConnectionTokenHashOk returns a tuple with the ConnectionTokenHash field value
// and a boolean to check if the value has been set.
func (o *IdentifyRequestBody) GetConnectionTokenHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionTokenHash, true
}

// SetConnectionTokenHash sets field value
func (o *IdentifyRequestBody) SetConnectionTokenHash(v string) {
	o.ConnectionTokenHash = v
}

// GetReturnTo returns the ReturnTo field value
func (o *IdentifyRequestBody) GetReturnTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReturnTo
}

// GetReturnToOk returns a tuple with the ReturnTo field value
// and a boolean to check if the value has been set.
func (o *IdentifyRequestBody) GetReturnToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReturnTo, true
}

// SetReturnTo sets field value
func (o *IdentifyRequestBody) SetReturnTo(v string) {
	o.ReturnTo = v
}

// GetLinkingToken returns the LinkingToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdentifyRequestBody) GetLinkingToken() string {
	if o == nil || IsNil(o.LinkingToken.Get()) {
		var ret string
		return ret
	}
	return *o.LinkingToken.Get()
}

// GetLinkingTokenOk returns a tuple with the LinkingToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentifyRequestBody) GetLinkingTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LinkingToken.Get(), o.LinkingToken.IsSet()
}

// HasLinkingToken returns a boolean if a field has been set.
func (o *IdentifyRequestBody) HasLinkingToken() bool {
	if o != nil && o.LinkingToken.IsSet() {
		return true
	}

	return false
}

// SetLinkingToken gets a reference to the given NullableString and assigns it to the LinkingToken field.
func (o *IdentifyRequestBody) SetLinkingToken(v string) {
	o.LinkingToken.Set(&v)
}
// SetLinkingTokenNil sets the value for LinkingToken to be an explicit nil
func (o *IdentifyRequestBody) SetLinkingTokenNil() {
	o.LinkingToken.Set(nil)
}

// UnsetLinkingToken ensures that no value is present for LinkingToken, not even an explicit nil
func (o *IdentifyRequestBody) UnsetLinkingToken() {
	o.LinkingToken.Unset()
}

func (o IdentifyRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentifyRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connection_nid"] = o.ConnectionNid
	toSerialize["connection_token_hash"] = o.ConnectionTokenHash
	toSerialize["return_to"] = o.ReturnTo
	if o.LinkingToken.IsSet() {
		toSerialize["linking_token"] = o.LinkingToken.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdentifyRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connection_nid",
		"connection_token_hash",
		"return_to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIdentifyRequestBody := _IdentifyRequestBody{}

	err = json.Unmarshal(data, &varIdentifyRequestBody)

	if err != nil {
		return err
	}

	*o = IdentifyRequestBody(varIdentifyRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "connection_nid")
		delete(additionalProperties, "connection_token_hash")
		delete(additionalProperties, "return_to")
		delete(additionalProperties, "linking_token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdentifyRequestBody struct {
	value *IdentifyRequestBody
	isSet bool
}

func (v NullableIdentifyRequestBody) Get() *IdentifyRequestBody {
	return v.value
}

func (v *NullableIdentifyRequestBody) Set(val *IdentifyRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentifyRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentifyRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentifyRequestBody(val *IdentifyRequestBody) *NullableIdentifyRequestBody {
	return &NullableIdentifyRequestBody{value: val, isSet: true}
}

func (v NullableIdentifyRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentifyRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


