/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
)

// checks if the CreateIdentifierResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIdentifierResponse{}

// CreateIdentifierResponse Response when creating an identifier
type CreateIdentifierResponse struct {
	// Whether the operation succeeded
	Success *int32 `json:"success,omitempty"`
	// The newly created identifier UUID
	Identifier *string `json:"identifier,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateIdentifierResponse CreateIdentifierResponse

// NewCreateIdentifierResponse instantiates a new CreateIdentifierResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIdentifierResponse() *CreateIdentifierResponse {
	this := CreateIdentifierResponse{}
	return &this
}

// NewCreateIdentifierResponseWithDefaults instantiates a new CreateIdentifierResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIdentifierResponseWithDefaults() *CreateIdentifierResponse {
	this := CreateIdentifierResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CreateIdentifierResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentifierResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CreateIdentifierResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *CreateIdentifierResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *CreateIdentifierResponse) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentifierResponse) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *CreateIdentifierResponse) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *CreateIdentifierResponse) SetIdentifier(v string) {
	o.Identifier = &v
}

func (o CreateIdentifierResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIdentifierResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateIdentifierResponse) UnmarshalJSON(data []byte) (err error) {
	varCreateIdentifierResponse := _CreateIdentifierResponse{}

	err = json.Unmarshal(data, &varCreateIdentifierResponse)

	if err != nil {
		return err
	}

	*o = CreateIdentifierResponse(varCreateIdentifierResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "identifier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateIdentifierResponse struct {
	value *CreateIdentifierResponse
	isSet bool
}

func (v NullableCreateIdentifierResponse) Get() *CreateIdentifierResponse {
	return v.value
}

func (v *NullableCreateIdentifierResponse) Set(val *CreateIdentifierResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIdentifierResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIdentifierResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIdentifierResponse(val *CreateIdentifierResponse) *NullableCreateIdentifierResponse {
	return &NullableCreateIdentifierResponse{value: val, isSet: true}
}

func (v NullableCreateIdentifierResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIdentifierResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


