/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
)

// checks if the GetInviteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInviteResponse{}

// GetInviteResponse Response when getting an invitation
type GetInviteResponse struct {
	Success *int32 `json:"success,omitempty"`
	// The invitation URL code
	InviteUrlCode *string `json:"invite_url_code,omitempty"`
	// The parent identifier UUID
	ParentUuid *string `json:"parent_uuid,omitempty"`
	// The application URL
	AppUrl *string `json:"app_url,omitempty"`
	// The OAuth2 client ID
	ClientId *string `json:"client_id,omitempty"`
	// The connection NID
	ConNid *string `json:"con_nid,omitempty"`
	// The organization ID
	OrgId NullableString `json:"org_id,omitempty"`
	// The project ID
	ProjectId NullableString `json:"project_id,omitempty"`
	// The item ID
	ItemId NullableString `json:"item_id,omitempty"`
	// The type of invitation
	Type *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetInviteResponse GetInviteResponse

// NewGetInviteResponse instantiates a new GetInviteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInviteResponse() *GetInviteResponse {
	this := GetInviteResponse{}
	return &this
}

// NewGetInviteResponseWithDefaults instantiates a new GetInviteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInviteResponseWithDefaults() *GetInviteResponse {
	this := GetInviteResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetInviteResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInviteResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetInviteResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *GetInviteResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetInviteUrlCode returns the InviteUrlCode field value if set, zero value otherwise.
func (o *GetInviteResponse) GetInviteUrlCode() string {
	if o == nil || IsNil(o.InviteUrlCode) {
		var ret string
		return ret
	}
	return *o.InviteUrlCode
}

// GetInviteUrlCodeOk returns a tuple with the InviteUrlCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInviteResponse) GetInviteUrlCodeOk() (*string, bool) {
	if o == nil || IsNil(o.InviteUrlCode) {
		return nil, false
	}
	return o.InviteUrlCode, true
}

// HasInviteUrlCode returns a boolean if a field has been set.
func (o *GetInviteResponse) HasInviteUrlCode() bool {
	if o != nil && !IsNil(o.InviteUrlCode) {
		return true
	}

	return false
}

// SetInviteUrlCode gets a reference to the given string and assigns it to the InviteUrlCode field.
func (o *GetInviteResponse) SetInviteUrlCode(v string) {
	o.InviteUrlCode = &v
}

// GetParentUuid returns the ParentUuid field value if set, zero value otherwise.
func (o *GetInviteResponse) GetParentUuid() string {
	if o == nil || IsNil(o.ParentUuid) {
		var ret string
		return ret
	}
	return *o.ParentUuid
}

// GetParentUuidOk returns a tuple with the ParentUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInviteResponse) GetParentUuidOk() (*string, bool) {
	if o == nil || IsNil(o.ParentUuid) {
		return nil, false
	}
	return o.ParentUuid, true
}

// HasParentUuid returns a boolean if a field has been set.
func (o *GetInviteResponse) HasParentUuid() bool {
	if o != nil && !IsNil(o.ParentUuid) {
		return true
	}

	return false
}

// SetParentUuid gets a reference to the given string and assigns it to the ParentUuid field.
func (o *GetInviteResponse) SetParentUuid(v string) {
	o.ParentUuid = &v
}

// GetAppUrl returns the AppUrl field value if set, zero value otherwise.
func (o *GetInviteResponse) GetAppUrl() string {
	if o == nil || IsNil(o.AppUrl) {
		var ret string
		return ret
	}
	return *o.AppUrl
}

// GetAppUrlOk returns a tuple with the AppUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInviteResponse) GetAppUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AppUrl) {
		return nil, false
	}
	return o.AppUrl, true
}

// HasAppUrl returns a boolean if a field has been set.
func (o *GetInviteResponse) HasAppUrl() bool {
	if o != nil && !IsNil(o.AppUrl) {
		return true
	}

	return false
}

// SetAppUrl gets a reference to the given string and assigns it to the AppUrl field.
func (o *GetInviteResponse) SetAppUrl(v string) {
	o.AppUrl = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *GetInviteResponse) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInviteResponse) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *GetInviteResponse) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *GetInviteResponse) SetClientId(v string) {
	o.ClientId = &v
}

// GetConNid returns the ConNid field value if set, zero value otherwise.
func (o *GetInviteResponse) GetConNid() string {
	if o == nil || IsNil(o.ConNid) {
		var ret string
		return ret
	}
	return *o.ConNid
}

// GetConNidOk returns a tuple with the ConNid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInviteResponse) GetConNidOk() (*string, bool) {
	if o == nil || IsNil(o.ConNid) {
		return nil, false
	}
	return o.ConNid, true
}

// HasConNid returns a boolean if a field has been set.
func (o *GetInviteResponse) HasConNid() bool {
	if o != nil && !IsNil(o.ConNid) {
		return true
	}

	return false
}

// SetConNid gets a reference to the given string and assigns it to the ConNid field.
func (o *GetInviteResponse) SetConNid(v string) {
	o.ConNid = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInviteResponse) GetOrgId() string {
	if o == nil || IsNil(o.OrgId.Get()) {
		var ret string
		return ret
	}
	return *o.OrgId.Get()
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInviteResponse) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrgId.Get(), o.OrgId.IsSet()
}

// HasOrgId returns a boolean if a field has been set.
func (o *GetInviteResponse) HasOrgId() bool {
	if o != nil && o.OrgId.IsSet() {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given NullableString and assigns it to the OrgId field.
func (o *GetInviteResponse) SetOrgId(v string) {
	o.OrgId.Set(&v)
}
// SetOrgIdNil sets the value for OrgId to be an explicit nil
func (o *GetInviteResponse) SetOrgIdNil() {
	o.OrgId.Set(nil)
}

// UnsetOrgId ensures that no value is present for OrgId, not even an explicit nil
func (o *GetInviteResponse) UnsetOrgId() {
	o.OrgId.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInviteResponse) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInviteResponse) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *GetInviteResponse) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *GetInviteResponse) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}
// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *GetInviteResponse) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *GetInviteResponse) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetItemId returns the ItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInviteResponse) GetItemId() string {
	if o == nil || IsNil(o.ItemId.Get()) {
		var ret string
		return ret
	}
	return *o.ItemId.Get()
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInviteResponse) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemId.Get(), o.ItemId.IsSet()
}

// HasItemId returns a boolean if a field has been set.
func (o *GetInviteResponse) HasItemId() bool {
	if o != nil && o.ItemId.IsSet() {
		return true
	}

	return false
}

// SetItemId gets a reference to the given NullableString and assigns it to the ItemId field.
func (o *GetInviteResponse) SetItemId(v string) {
	o.ItemId.Set(&v)
}
// SetItemIdNil sets the value for ItemId to be an explicit nil
func (o *GetInviteResponse) SetItemIdNil() {
	o.ItemId.Set(nil)
}

// UnsetItemId ensures that no value is present for ItemId, not even an explicit nil
func (o *GetInviteResponse) UnsetItemId() {
	o.ItemId.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetInviteResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInviteResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetInviteResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetInviteResponse) SetType(v string) {
	o.Type = &v
}

func (o GetInviteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInviteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.InviteUrlCode) {
		toSerialize["invite_url_code"] = o.InviteUrlCode
	}
	if !IsNil(o.ParentUuid) {
		toSerialize["parent_uuid"] = o.ParentUuid
	}
	if !IsNil(o.AppUrl) {
		toSerialize["app_url"] = o.AppUrl
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ConNid) {
		toSerialize["con_nid"] = o.ConNid
	}
	if o.OrgId.IsSet() {
		toSerialize["org_id"] = o.OrgId.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["project_id"] = o.ProjectId.Get()
	}
	if o.ItemId.IsSet() {
		toSerialize["item_id"] = o.ItemId.Get()
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetInviteResponse) UnmarshalJSON(data []byte) (err error) {
	varGetInviteResponse := _GetInviteResponse{}

	err = json.Unmarshal(data, &varGetInviteResponse)

	if err != nil {
		return err
	}

	*o = GetInviteResponse(varGetInviteResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "invite_url_code")
		delete(additionalProperties, "parent_uuid")
		delete(additionalProperties, "app_url")
		delete(additionalProperties, "client_id")
		delete(additionalProperties, "con_nid")
		delete(additionalProperties, "org_id")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "item_id")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetInviteResponse struct {
	value *GetInviteResponse
	isSet bool
}

func (v NullableGetInviteResponse) Get() *GetInviteResponse {
	return v.value
}

func (v *NullableGetInviteResponse) Set(val *GetInviteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInviteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInviteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInviteResponse(val *GetInviteResponse) *NullableGetInviteResponse {
	return &NullableGetInviteResponse{value: val, isSet: true}
}

func (v NullableGetInviteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInviteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


