/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
)

// checks if the GetIdentifiersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIdentifiersResponse{}

// GetIdentifiersResponse Response when getting all identifiers for a member
type GetIdentifiersResponse struct {
	Success *int32 `json:"success,omitempty"`
	Identifiers []IdentifierObject `json:"identifiers,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetIdentifiersResponse GetIdentifiersResponse

// NewGetIdentifiersResponse instantiates a new GetIdentifiersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIdentifiersResponse() *GetIdentifiersResponse {
	this := GetIdentifiersResponse{}
	return &this
}

// NewGetIdentifiersResponseWithDefaults instantiates a new GetIdentifiersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIdentifiersResponseWithDefaults() *GetIdentifiersResponse {
	this := GetIdentifiersResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetIdentifiersResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIdentifiersResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetIdentifiersResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *GetIdentifiersResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetIdentifiers returns the Identifiers field value if set, zero value otherwise.
func (o *GetIdentifiersResponse) GetIdentifiers() []IdentifierObject {
	if o == nil || IsNil(o.Identifiers) {
		var ret []IdentifierObject
		return ret
	}
	return o.Identifiers
}

// GetIdentifiersOk returns a tuple with the Identifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIdentifiersResponse) GetIdentifiersOk() ([]IdentifierObject, bool) {
	if o == nil || IsNil(o.Identifiers) {
		return nil, false
	}
	return o.Identifiers, true
}

// HasIdentifiers returns a boolean if a field has been set.
func (o *GetIdentifiersResponse) HasIdentifiers() bool {
	if o != nil && !IsNil(o.Identifiers) {
		return true
	}

	return false
}

// SetIdentifiers gets a reference to the given []IdentifierObject and assigns it to the Identifiers field.
func (o *GetIdentifiersResponse) SetIdentifiers(v []IdentifierObject) {
	o.Identifiers = v
}

func (o GetIdentifiersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIdentifiersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Identifiers) {
		toSerialize["identifiers"] = o.Identifiers
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetIdentifiersResponse) UnmarshalJSON(data []byte) (err error) {
	varGetIdentifiersResponse := _GetIdentifiersResponse{}

	err = json.Unmarshal(data, &varGetIdentifiersResponse)

	if err != nil {
		return err
	}

	*o = GetIdentifiersResponse(varGetIdentifiersResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "identifiers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetIdentifiersResponse struct {
	value *GetIdentifiersResponse
	isSet bool
}

func (v NullableGetIdentifiersResponse) Get() *GetIdentifiersResponse {
	return v.value
}

func (v *NullableGetIdentifiersResponse) Set(val *GetIdentifiersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIdentifiersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIdentifiersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIdentifiersResponse(val *GetIdentifiersResponse) *NullableGetIdentifiersResponse {
	return &NullableGetIdentifiersResponse{value: val, isSet: true}
}

func (v NullableGetIdentifiersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIdentifiersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


