/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
)

// checks if the InviteStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteStatusResponse{}

// InviteStatusResponse Response for checking invite status
type InviteStatusResponse struct {
	// Whether the invite exists
	Success *int32 `json:"success,omitempty"`
	// The status of the invite (pending, used, expired)
	Status *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InviteStatusResponse InviteStatusResponse

// NewInviteStatusResponse instantiates a new InviteStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteStatusResponse() *InviteStatusResponse {
	this := InviteStatusResponse{}
	return &this
}

// NewInviteStatusResponseWithDefaults instantiates a new InviteStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteStatusResponseWithDefaults() *InviteStatusResponse {
	this := InviteStatusResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *InviteStatusResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteStatusResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *InviteStatusResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *InviteStatusResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InviteStatusResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InviteStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *InviteStatusResponse) SetStatus(v string) {
	o.Status = &v
}

func (o InviteStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InviteStatusResponse) UnmarshalJSON(data []byte) (err error) {
	varInviteStatusResponse := _InviteStatusResponse{}

	err = json.Unmarshal(data, &varInviteStatusResponse)

	if err != nil {
		return err
	}

	*o = InviteStatusResponse(varInviteStatusResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInviteStatusResponse struct {
	value *InviteStatusResponse
	isSet bool
}

func (v NullableInviteStatusResponse) Get() *InviteStatusResponse {
	return v.value
}

func (v *NullableInviteStatusResponse) Set(val *InviteStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteStatusResponse(val *InviteStatusResponse) *NullableInviteStatusResponse {
	return &NullableInviteStatusResponse{value: val, isSet: true}
}

func (v NullableInviteStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


