/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
)

// checks if the IdentifierObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentifierObject{}

// IdentifierObject An identifier record
type IdentifierObject struct {
	// Database ID of the identifier
	Id *string `json:"id,omitempty"`
	// The UUID identifier
	Identifier *string `json:"identifier,omitempty"`
	// The parent identifier UUID if this is a child
	ParentUuid NullableString `json:"parent_uuid,omitempty"`
	// The type of identifier
	Type *string `json:"type,omitempty"`
	// Creation timestamp
	Created *string `json:"created,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IdentifierObject IdentifierObject

// NewIdentifierObject instantiates a new IdentifierObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentifierObject() *IdentifierObject {
	this := IdentifierObject{}
	return &this
}

// NewIdentifierObjectWithDefaults instantiates a new IdentifierObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentifierObjectWithDefaults() *IdentifierObject {
	this := IdentifierObject{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IdentifierObject) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierObject) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IdentifierObject) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IdentifierObject) SetId(v string) {
	o.Id = &v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *IdentifierObject) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierObject) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *IdentifierObject) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *IdentifierObject) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetParentUuid returns the ParentUuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdentifierObject) GetParentUuid() string {
	if o == nil || IsNil(o.ParentUuid.Get()) {
		var ret string
		return ret
	}
	return *o.ParentUuid.Get()
}

// GetParentUuidOk returns a tuple with the ParentUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentifierObject) GetParentUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentUuid.Get(), o.ParentUuid.IsSet()
}

// HasParentUuid returns a boolean if a field has been set.
func (o *IdentifierObject) HasParentUuid() bool {
	if o != nil && o.ParentUuid.IsSet() {
		return true
	}

	return false
}

// SetParentUuid gets a reference to the given NullableString and assigns it to the ParentUuid field.
func (o *IdentifierObject) SetParentUuid(v string) {
	o.ParentUuid.Set(&v)
}
// SetParentUuidNil sets the value for ParentUuid to be an explicit nil
func (o *IdentifierObject) SetParentUuidNil() {
	o.ParentUuid.Set(nil)
}

// UnsetParentUuid ensures that no value is present for ParentUuid, not even an explicit nil
func (o *IdentifierObject) UnsetParentUuid() {
	o.ParentUuid.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IdentifierObject) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierObject) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IdentifierObject) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IdentifierObject) SetType(v string) {
	o.Type = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *IdentifierObject) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierObject) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *IdentifierObject) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *IdentifierObject) SetCreated(v string) {
	o.Created = &v
}

func (o IdentifierObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentifierObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	if o.ParentUuid.IsSet() {
		toSerialize["parent_uuid"] = o.ParentUuid.Get()
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdentifierObject) UnmarshalJSON(data []byte) (err error) {
	varIdentifierObject := _IdentifierObject{}

	err = json.Unmarshal(data, &varIdentifierObject)

	if err != nil {
		return err
	}

	*o = IdentifierObject(varIdentifierObject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "identifier")
		delete(additionalProperties, "parent_uuid")
		delete(additionalProperties, "type")
		delete(additionalProperties, "created")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdentifierObject struct {
	value *IdentifierObject
	isSet bool
}

func (v NullableIdentifierObject) Get() *IdentifierObject {
	return v.value
}

func (v *NullableIdentifierObject) Set(val *IdentifierObject) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentifierObject) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentifierObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentifierObject(val *IdentifierObject) *NullableIdentifierObject {
	return &NullableIdentifierObject{value: val, isSet: true}
}

func (v NullableIdentifierObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentifierObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


