/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
	"fmt"
)

// checks if the FtcSetupRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FtcSetupRequestBody{}

// FtcSetupRequestBody Request body for First Time Connection setup
type FtcSetupRequestBody struct {
	// The connection NID
	ConnectionNid string `json:"connection_nid"`
	// The hashed connection token
	ConnectionTokenHash string `json:"connection_token_hash"`
	// The URL to return to after connection
	ReturnTo string `json:"return_to"`
	// The MydexID if already known (required if version > 1)
	Mydexid NullableString `json:"mydexid,omitempty"`
	// The connection version (default 1, must be >= 1)
	Version *int32 `json:"version,omitempty"`
	// A unique ID representing the member in the subscriber's backend
	LinkingToken NullableString `json:"linking_token,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FtcSetupRequestBody FtcSetupRequestBody

// NewFtcSetupRequestBody instantiates a new FtcSetupRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFtcSetupRequestBody(connectionNid string, connectionTokenHash string, returnTo string) *FtcSetupRequestBody {
	this := FtcSetupRequestBody{}
	this.ConnectionNid = connectionNid
	this.ConnectionTokenHash = connectionTokenHash
	this.ReturnTo = returnTo
	return &this
}

// NewFtcSetupRequestBodyWithDefaults instantiates a new FtcSetupRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFtcSetupRequestBodyWithDefaults() *FtcSetupRequestBody {
	this := FtcSetupRequestBody{}
	return &this
}

// GetConnectionNid returns the ConnectionNid field value
func (o *FtcSetupRequestBody) GetConnectionNid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionNid
}

// GetConnectionNidOk returns a tuple with the ConnectionNid field value
// and a boolean to check if the value has been set.
func (o *FtcSetupRequestBody) GetConnectionNidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionNid, true
}

// SetConnectionNid sets field value
func (o *FtcSetupRequestBody) SetConnectionNid(v string) {
	o.ConnectionNid = v
}

// GetConnectionTokenHash returns the ConnectionTokenHash field value
func (o *FtcSetupRequestBody) GetConnectionTokenHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionTokenHash
}

// GetConnectionTokenHashOk returns a tuple with the ConnectionTokenHash field value
// and a boolean to check if the value has been set.
func (o *FtcSetupRequestBody) GetConnectionTokenHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionTokenHash, true
}

// SetConnectionTokenHash sets field value
func (o *FtcSetupRequestBody) SetConnectionTokenHash(v string) {
	o.ConnectionTokenHash = v
}

// GetReturnTo returns the ReturnTo field value
func (o *FtcSetupRequestBody) GetReturnTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReturnTo
}

// GetReturnToOk returns a tuple with the ReturnTo field value
// and a boolean to check if the value has been set.
func (o *FtcSetupRequestBody) GetReturnToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReturnTo, true
}

// SetReturnTo sets field value
func (o *FtcSetupRequestBody) SetReturnTo(v string) {
	o.ReturnTo = v
}

// GetMydexid returns the Mydexid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FtcSetupRequestBody) GetMydexid() string {
	if o == nil || IsNil(o.Mydexid.Get()) {
		var ret string
		return ret
	}
	return *o.Mydexid.Get()
}

// GetMydexidOk returns a tuple with the Mydexid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FtcSetupRequestBody) GetMydexidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mydexid.Get(), o.Mydexid.IsSet()
}

// HasMydexid returns a boolean if a field has been set.
func (o *FtcSetupRequestBody) HasMydexid() bool {
	if o != nil && o.Mydexid.IsSet() {
		return true
	}

	return false
}

// SetMydexid gets a reference to the given NullableString and assigns it to the Mydexid field.
func (o *FtcSetupRequestBody) SetMydexid(v string) {
	o.Mydexid.Set(&v)
}
// SetMydexidNil sets the value for Mydexid to be an explicit nil
func (o *FtcSetupRequestBody) SetMydexidNil() {
	o.Mydexid.Set(nil)
}

// UnsetMydexid ensures that no value is present for Mydexid, not even an explicit nil
func (o *FtcSetupRequestBody) UnsetMydexid() {
	o.Mydexid.Unset()
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *FtcSetupRequestBody) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FtcSetupRequestBody) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *FtcSetupRequestBody) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *FtcSetupRequestBody) SetVersion(v int32) {
	o.Version = &v
}

// GetLinkingToken returns the LinkingToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FtcSetupRequestBody) GetLinkingToken() string {
	if o == nil || IsNil(o.LinkingToken.Get()) {
		var ret string
		return ret
	}
	return *o.LinkingToken.Get()
}

// GetLinkingTokenOk returns a tuple with the LinkingToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FtcSetupRequestBody) GetLinkingTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LinkingToken.Get(), o.LinkingToken.IsSet()
}

// HasLinkingToken returns a boolean if a field has been set.
func (o *FtcSetupRequestBody) HasLinkingToken() bool {
	if o != nil && o.LinkingToken.IsSet() {
		return true
	}

	return false
}

// SetLinkingToken gets a reference to the given NullableString and assigns it to the LinkingToken field.
func (o *FtcSetupRequestBody) SetLinkingToken(v string) {
	o.LinkingToken.Set(&v)
}
// SetLinkingTokenNil sets the value for LinkingToken to be an explicit nil
func (o *FtcSetupRequestBody) SetLinkingTokenNil() {
	o.LinkingToken.Set(nil)
}

// UnsetLinkingToken ensures that no value is present for LinkingToken, not even an explicit nil
func (o *FtcSetupRequestBody) UnsetLinkingToken() {
	o.LinkingToken.Unset()
}

func (o FtcSetupRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FtcSetupRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connection_nid"] = o.ConnectionNid
	toSerialize["connection_token_hash"] = o.ConnectionTokenHash
	toSerialize["return_to"] = o.ReturnTo
	if o.Mydexid.IsSet() {
		toSerialize["mydexid"] = o.Mydexid.Get()
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if o.LinkingToken.IsSet() {
		toSerialize["linking_token"] = o.LinkingToken.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FtcSetupRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connection_nid",
		"connection_token_hash",
		"return_to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFtcSetupRequestBody := _FtcSetupRequestBody{}

	err = json.Unmarshal(data, &varFtcSetupRequestBody)

	if err != nil {
		return err
	}

	*o = FtcSetupRequestBody(varFtcSetupRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "connection_nid")
		delete(additionalProperties, "connection_token_hash")
		delete(additionalProperties, "return_to")
		delete(additionalProperties, "mydexid")
		delete(additionalProperties, "version")
		delete(additionalProperties, "linking_token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFtcSetupRequestBody struct {
	value *FtcSetupRequestBody
	isSet bool
}

func (v NullableFtcSetupRequestBody) Get() *FtcSetupRequestBody {
	return v.value
}

func (v *NullableFtcSetupRequestBody) Set(val *FtcSetupRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableFtcSetupRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableFtcSetupRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFtcSetupRequestBody(val *FtcSetupRequestBody) *NullableFtcSetupRequestBody {
	return &NullableFtcSetupRequestBody{value: val, isSet: true}
}

func (v NullableFtcSetupRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFtcSetupRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


