/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
)

// checks if the IdentifierAuthObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentifierAuthObject{}

// IdentifierAuthObject Authentication data for an identifier
type IdentifierAuthObject struct {
	// The parent identifier UUID
	ParentUuid *string `json:"parent_uuid,omitempty"`
	// The application URL
	AppUrl *string `json:"app_url,omitempty"`
	// The OAuth2 client ID
	ClientId *string `json:"client_id,omitempty"`
	// The connection NID
	ConNid *string `json:"con_nid,omitempty"`
	// The organization ID
	OrgId *string `json:"org_id,omitempty"`
	// The project ID
	ProjectId *string `json:"project_id,omitempty"`
	// The item ID
	ItemId *string `json:"item_id,omitempty"`
	// The type of identifier/auth
	Type *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IdentifierAuthObject IdentifierAuthObject

// NewIdentifierAuthObject instantiates a new IdentifierAuthObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentifierAuthObject() *IdentifierAuthObject {
	this := IdentifierAuthObject{}
	return &this
}

// NewIdentifierAuthObjectWithDefaults instantiates a new IdentifierAuthObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentifierAuthObjectWithDefaults() *IdentifierAuthObject {
	this := IdentifierAuthObject{}
	return &this
}

// GetParentUuid returns the ParentUuid field value if set, zero value otherwise.
func (o *IdentifierAuthObject) GetParentUuid() string {
	if o == nil || IsNil(o.ParentUuid) {
		var ret string
		return ret
	}
	return *o.ParentUuid
}

// GetParentUuidOk returns a tuple with the ParentUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierAuthObject) GetParentUuidOk() (*string, bool) {
	if o == nil || IsNil(o.ParentUuid) {
		return nil, false
	}
	return o.ParentUuid, true
}

// HasParentUuid returns a boolean if a field has been set.
func (o *IdentifierAuthObject) HasParentUuid() bool {
	if o != nil && !IsNil(o.ParentUuid) {
		return true
	}

	return false
}

// SetParentUuid gets a reference to the given string and assigns it to the ParentUuid field.
func (o *IdentifierAuthObject) SetParentUuid(v string) {
	o.ParentUuid = &v
}

// GetAppUrl returns the AppUrl field value if set, zero value otherwise.
func (o *IdentifierAuthObject) GetAppUrl() string {
	if o == nil || IsNil(o.AppUrl) {
		var ret string
		return ret
	}
	return *o.AppUrl
}

// GetAppUrlOk returns a tuple with the AppUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierAuthObject) GetAppUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AppUrl) {
		return nil, false
	}
	return o.AppUrl, true
}

// HasAppUrl returns a boolean if a field has been set.
func (o *IdentifierAuthObject) HasAppUrl() bool {
	if o != nil && !IsNil(o.AppUrl) {
		return true
	}

	return false
}

// SetAppUrl gets a reference to the given string and assigns it to the AppUrl field.
func (o *IdentifierAuthObject) SetAppUrl(v string) {
	o.AppUrl = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *IdentifierAuthObject) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierAuthObject) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *IdentifierAuthObject) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *IdentifierAuthObject) SetClientId(v string) {
	o.ClientId = &v
}

// GetConNid returns the ConNid field value if set, zero value otherwise.
func (o *IdentifierAuthObject) GetConNid() string {
	if o == nil || IsNil(o.ConNid) {
		var ret string
		return ret
	}
	return *o.ConNid
}

// GetConNidOk returns a tuple with the ConNid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierAuthObject) GetConNidOk() (*string, bool) {
	if o == nil || IsNil(o.ConNid) {
		return nil, false
	}
	return o.ConNid, true
}

// HasConNid returns a boolean if a field has been set.
func (o *IdentifierAuthObject) HasConNid() bool {
	if o != nil && !IsNil(o.ConNid) {
		return true
	}

	return false
}

// SetConNid gets a reference to the given string and assigns it to the ConNid field.
func (o *IdentifierAuthObject) SetConNid(v string) {
	o.ConNid = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *IdentifierAuthObject) GetOrgId() string {
	if o == nil || IsNil(o.OrgId) {
		var ret string
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierAuthObject) GetOrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *IdentifierAuthObject) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given string and assigns it to the OrgId field.
func (o *IdentifierAuthObject) SetOrgId(v string) {
	o.OrgId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *IdentifierAuthObject) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierAuthObject) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *IdentifierAuthObject) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *IdentifierAuthObject) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetItemId returns the ItemId field value if set, zero value otherwise.
func (o *IdentifierAuthObject) GetItemId() string {
	if o == nil || IsNil(o.ItemId) {
		var ret string
		return ret
	}
	return *o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierAuthObject) GetItemIdOk() (*string, bool) {
	if o == nil || IsNil(o.ItemId) {
		return nil, false
	}
	return o.ItemId, true
}

// HasItemId returns a boolean if a field has been set.
func (o *IdentifierAuthObject) HasItemId() bool {
	if o != nil && !IsNil(o.ItemId) {
		return true
	}

	return false
}

// SetItemId gets a reference to the given string and assigns it to the ItemId field.
func (o *IdentifierAuthObject) SetItemId(v string) {
	o.ItemId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IdentifierAuthObject) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifierAuthObject) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IdentifierAuthObject) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IdentifierAuthObject) SetType(v string) {
	o.Type = &v
}

func (o IdentifierAuthObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentifierAuthObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ParentUuid) {
		toSerialize["parent_uuid"] = o.ParentUuid
	}
	if !IsNil(o.AppUrl) {
		toSerialize["app_url"] = o.AppUrl
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ConNid) {
		toSerialize["con_nid"] = o.ConNid
	}
	if !IsNil(o.OrgId) {
		toSerialize["org_id"] = o.OrgId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.ItemId) {
		toSerialize["item_id"] = o.ItemId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdentifierAuthObject) UnmarshalJSON(data []byte) (err error) {
	varIdentifierAuthObject := _IdentifierAuthObject{}

	err = json.Unmarshal(data, &varIdentifierAuthObject)

	if err != nil {
		return err
	}

	*o = IdentifierAuthObject(varIdentifierAuthObject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "parent_uuid")
		delete(additionalProperties, "app_url")
		delete(additionalProperties, "client_id")
		delete(additionalProperties, "con_nid")
		delete(additionalProperties, "org_id")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "item_id")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdentifierAuthObject struct {
	value *IdentifierAuthObject
	isSet bool
}

func (v NullableIdentifierAuthObject) Get() *IdentifierAuthObject {
	return v.value
}

func (v *NullableIdentifierAuthObject) Set(val *IdentifierAuthObject) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentifierAuthObject) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentifierAuthObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentifierAuthObject(val *IdentifierAuthObject) *NullableIdentifierAuthObject {
	return &NullableIdentifierAuthObject{value: val, isSet: true}
}

func (v NullableIdentifierAuthObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentifierAuthObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


