/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateNotificationStatusRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNotificationStatusRequestBody{}

// UpdateNotificationStatusRequestBody Request body for updating notification status
type UpdateNotificationStatusRequestBody struct {
	// The notification identifier to update
	Identifier string `json:"identifier"`
	AdditionalProperties map[string]interface{}
}

type _UpdateNotificationStatusRequestBody UpdateNotificationStatusRequestBody

// NewUpdateNotificationStatusRequestBody instantiates a new UpdateNotificationStatusRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNotificationStatusRequestBody(identifier string) *UpdateNotificationStatusRequestBody {
	this := UpdateNotificationStatusRequestBody{}
	this.Identifier = identifier
	return &this
}

// NewUpdateNotificationStatusRequestBodyWithDefaults instantiates a new UpdateNotificationStatusRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNotificationStatusRequestBodyWithDefaults() *UpdateNotificationStatusRequestBody {
	this := UpdateNotificationStatusRequestBody{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *UpdateNotificationStatusRequestBody) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *UpdateNotificationStatusRequestBody) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *UpdateNotificationStatusRequestBody) SetIdentifier(v string) {
	o.Identifier = v
}

func (o UpdateNotificationStatusRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNotificationStatusRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateNotificationStatusRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateNotificationStatusRequestBody := _UpdateNotificationStatusRequestBody{}

	err = json.Unmarshal(data, &varUpdateNotificationStatusRequestBody)

	if err != nil {
		return err
	}

	*o = UpdateNotificationStatusRequestBody(varUpdateNotificationStatusRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "identifier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateNotificationStatusRequestBody struct {
	value *UpdateNotificationStatusRequestBody
	isSet bool
}

func (v NullableUpdateNotificationStatusRequestBody) Get() *UpdateNotificationStatusRequestBody {
	return v.value
}

func (v *NullableUpdateNotificationStatusRequestBody) Set(val *UpdateNotificationStatusRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNotificationStatusRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNotificationStatusRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNotificationStatusRequestBody(val *UpdateNotificationStatusRequestBody) *NullableUpdateNotificationStatusRequestBody {
	return &NullableUpdateNotificationStatusRequestBody{value: val, isSet: true}
}

func (v NullableUpdateNotificationStatusRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNotificationStatusRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


