/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
	"fmt"
)

// checks if the InviteStatusRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteStatusRequestBody{}

// InviteStatusRequestBody Request body for checking invite status
type InviteStatusRequestBody struct {
	// The parent identifier
	Identifier string `json:"identifier"`
	AppUrl string `json:"app_url"`
	ClientId string `json:"client_id"`
	ConNid string `json:"con_nid"`
	OrgId string `json:"org_id"`
	ProjectId string `json:"project_id"`
	ItemId string `json:"item_id"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _InviteStatusRequestBody InviteStatusRequestBody

// NewInviteStatusRequestBody instantiates a new InviteStatusRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteStatusRequestBody(identifier string, appUrl string, clientId string, conNid string, orgId string, projectId string, itemId string, type_ string) *InviteStatusRequestBody {
	this := InviteStatusRequestBody{}
	this.Identifier = identifier
	this.AppUrl = appUrl
	this.ClientId = clientId
	this.ConNid = conNid
	this.OrgId = orgId
	this.ProjectId = projectId
	this.ItemId = itemId
	this.Type = type_
	return &this
}

// NewInviteStatusRequestBodyWithDefaults instantiates a new InviteStatusRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteStatusRequestBodyWithDefaults() *InviteStatusRequestBody {
	this := InviteStatusRequestBody{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *InviteStatusRequestBody) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *InviteStatusRequestBody) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *InviteStatusRequestBody) SetIdentifier(v string) {
	o.Identifier = v
}

// GetAppUrl returns the AppUrl field value
func (o *InviteStatusRequestBody) GetAppUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppUrl
}

// GetAppUrlOk returns a tuple with the AppUrl field value
// and a boolean to check if the value has been set.
func (o *InviteStatusRequestBody) GetAppUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppUrl, true
}

// SetAppUrl sets field value
func (o *InviteStatusRequestBody) SetAppUrl(v string) {
	o.AppUrl = v
}

// GetClientId returns the ClientId field value
func (o *InviteStatusRequestBody) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *InviteStatusRequestBody) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *InviteStatusRequestBody) SetClientId(v string) {
	o.ClientId = v
}

// GetConNid returns the ConNid field value
func (o *InviteStatusRequestBody) GetConNid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConNid
}

// GetConNidOk returns a tuple with the ConNid field value
// and a boolean to check if the value has been set.
func (o *InviteStatusRequestBody) GetConNidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConNid, true
}

// SetConNid sets field value
func (o *InviteStatusRequestBody) SetConNid(v string) {
	o.ConNid = v
}

// GetOrgId returns the OrgId field value
func (o *InviteStatusRequestBody) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *InviteStatusRequestBody) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *InviteStatusRequestBody) SetOrgId(v string) {
	o.OrgId = v
}

// GetProjectId returns the ProjectId field value
func (o *InviteStatusRequestBody) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *InviteStatusRequestBody) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *InviteStatusRequestBody) SetProjectId(v string) {
	o.ProjectId = v
}

// GetItemId returns the ItemId field value
func (o *InviteStatusRequestBody) GetItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value
// and a boolean to check if the value has been set.
func (o *InviteStatusRequestBody) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemId, true
}

// SetItemId sets field value
func (o *InviteStatusRequestBody) SetItemId(v string) {
	o.ItemId = v
}

// GetType returns the Type field value
func (o *InviteStatusRequestBody) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InviteStatusRequestBody) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InviteStatusRequestBody) SetType(v string) {
	o.Type = v
}

func (o InviteStatusRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteStatusRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	toSerialize["app_url"] = o.AppUrl
	toSerialize["client_id"] = o.ClientId
	toSerialize["con_nid"] = o.ConNid
	toSerialize["org_id"] = o.OrgId
	toSerialize["project_id"] = o.ProjectId
	toSerialize["item_id"] = o.ItemId
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InviteStatusRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
		"app_url",
		"client_id",
		"con_nid",
		"org_id",
		"project_id",
		"item_id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteStatusRequestBody := _InviteStatusRequestBody{}

	err = json.Unmarshal(data, &varInviteStatusRequestBody)

	if err != nil {
		return err
	}

	*o = InviteStatusRequestBody(varInviteStatusRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "identifier")
		delete(additionalProperties, "app_url")
		delete(additionalProperties, "client_id")
		delete(additionalProperties, "con_nid")
		delete(additionalProperties, "org_id")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "item_id")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInviteStatusRequestBody struct {
	value *InviteStatusRequestBody
	isSet bool
}

func (v NullableInviteStatusRequestBody) Get() *InviteStatusRequestBody {
	return v.value
}

func (v *NullableInviteStatusRequestBody) Set(val *InviteStatusRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteStatusRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteStatusRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteStatusRequestBody(val *InviteStatusRequestBody) *NullableInviteStatusRequestBody {
	return &NullableInviteStatusRequestBody{value: val, isSet: true}
}

func (v NullableInviteStatusRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteStatusRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


