/*
IDaaS API

Identity as a Service API for member authentication, identifiers, and account management.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiidaassdk

import (
	"encoding/json"
)

// checks if the FtcIdentifyUrlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FtcIdentifyUrlResponse{}

// FtcIdentifyUrlResponse Response containing the FTC or Identify URL and QR code
type FtcIdentifyUrlResponse struct {
	// The one-time URL for FTC or identification
	Url *string `json:"url,omitempty"`
	// QR code representation of the URL
	Qr *string `json:"qr,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FtcIdentifyUrlResponse FtcIdentifyUrlResponse

// NewFtcIdentifyUrlResponse instantiates a new FtcIdentifyUrlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFtcIdentifyUrlResponse() *FtcIdentifyUrlResponse {
	this := FtcIdentifyUrlResponse{}
	return &this
}

// NewFtcIdentifyUrlResponseWithDefaults instantiates a new FtcIdentifyUrlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFtcIdentifyUrlResponseWithDefaults() *FtcIdentifyUrlResponse {
	this := FtcIdentifyUrlResponse{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *FtcIdentifyUrlResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FtcIdentifyUrlResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *FtcIdentifyUrlResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *FtcIdentifyUrlResponse) SetUrl(v string) {
	o.Url = &v
}

// GetQr returns the Qr field value if set, zero value otherwise.
func (o *FtcIdentifyUrlResponse) GetQr() string {
	if o == nil || IsNil(o.Qr) {
		var ret string
		return ret
	}
	return *o.Qr
}

// GetQrOk returns a tuple with the Qr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FtcIdentifyUrlResponse) GetQrOk() (*string, bool) {
	if o == nil || IsNil(o.Qr) {
		return nil, false
	}
	return o.Qr, true
}

// HasQr returns a boolean if a field has been set.
func (o *FtcIdentifyUrlResponse) HasQr() bool {
	if o != nil && !IsNil(o.Qr) {
		return true
	}

	return false
}

// SetQr gets a reference to the given string and assigns it to the Qr field.
func (o *FtcIdentifyUrlResponse) SetQr(v string) {
	o.Qr = &v
}

func (o FtcIdentifyUrlResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FtcIdentifyUrlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Qr) {
		toSerialize["qr"] = o.Qr
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FtcIdentifyUrlResponse) UnmarshalJSON(data []byte) (err error) {
	varFtcIdentifyUrlResponse := _FtcIdentifyUrlResponse{}

	err = json.Unmarshal(data, &varFtcIdentifyUrlResponse)

	if err != nil {
		return err
	}

	*o = FtcIdentifyUrlResponse(varFtcIdentifyUrlResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "qr")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFtcIdentifyUrlResponse struct {
	value *FtcIdentifyUrlResponse
	isSet bool
}

func (v NullableFtcIdentifyUrlResponse) Get() *FtcIdentifyUrlResponse {
	return v.value
}

func (v *NullableFtcIdentifyUrlResponse) Set(val *FtcIdentifyUrlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFtcIdentifyUrlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFtcIdentifyUrlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFtcIdentifyUrlResponse(val *FtcIdentifyUrlResponse) *NullableFtcIdentifyUrlResponse {
	return &NullableFtcIdentifyUrlResponse{value: val, isSet: true}
}

func (v NullableFtcIdentifyUrlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFtcIdentifyUrlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


